CREATE TABLE Bookings (
    Id VARCHAR(255) PRIMARY KEY,
    UserId  VARCHAR(255) FOREIGN KEY REFERENCES Users (Id) ON DELETE CASCADE,
    TourId  VARCHAR(255) FOREIGN KEY REFERENCES  Tours(Id), 
    HotelId  VARCHAR(255) FOREIGN KEY REFERENCES  Hotels(Id),
    BookingDate DATE, 
    isEmailSent int DEFAULT 0
)